### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by YuelongLi** [sstrickx/yahoofinance-api#104]
I've been having this issue when requesting stocks recently. 
Here's a trace of the exception:
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at yahoofinance.quotes.QuotesRequest.<clinit>(QuotesRequest.java:28)
	at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:357)
	at yahoofinance.YahooFinance.get(YahooFinance.java:88)
	at yahoofinance.YahooFinance.get(YahooFinance.java:72)
	at runTests.APIStockRequest.main(APIStockRequest.java:13)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more

**Comment by sstrickx** [comment]
Hi, this is probably related to your personal setup.
For some reason the classloader is unable to find `org.slf4j.LoggerFactory`, which is provided by the artifact `slf4j-api`. This artifact is correctly defined as a dependency in the pom file.
If you're not using maven, make sure that all the required dependencies are on the classpath.

**Comment by YuelongLi** [comment]
Thank you, the problem is fixed now. 
I have downloaded a library from this https://www.slf4j.org/download.html site and imported slf4j-api-1.7.25.jar and slf4j-nop-1.7.25.jar onto my java build path. Hopefully this can help with other users having similar issues.
