### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by kejuntong** [sstrickx/yahoofinance-api#106]
It looks like YahooFinance stop supporting the api..

-----------------------------------------------------------
java.io.FileNotFoundException: http://download.finance.yahoo.com/d/quotes.csv?s=CR.TO&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8s7&e=.csv
     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:254)
     at yahoofinance.quotes.QuotesRequest.getResult(QuotesRequest.java:93)
     at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:358)
     at yahoofinance.YahooFinance.get(YahooFinance.java:88)
-----------------------------------------------------------

It has come to our attention that this service is being used in violation of the Yahoo Terms of Service. As such, the service is being discontinued. For all future markets and equities data research, please refer to finance.yahoo.com.

**Comment by Hoffs-** [comment]
duplicate https://github.com/sstrickx/yahoofinance-api/issues/105
