### ISSUE TITLE
Index query (^DJI) -  NullPointerException 

### ISSUE THREAD

**Issue by plegula** [sstrickx/yahoofinance-api#107]
YahooFinance.get("^DJI");

Lack of "longName" filed in node. 
stock.setName(node.get("longName").asText());

java.lang.NullPointerException
	at yahoofinance.quotes.query1v7.StockQuotesQuery1V7Request.parseJson(StockQuotesQuery1V7Request.java:30)
	at yahoofinance.quotes.query1v7.StockQuotesQuery1V7Request.parseJson(StockQuotesQuery1V7Request.java:17)
	at yahoofinance.quotes.query1v7.QuotesRequest.getResult(QuotesRequest.java:79)
	at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:375)
	at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:398)
	at yahoofinance.YahooFinance.get(YahooFinance.java:272)

**Comment by plegula** [comment]
Hm strange,  it happend few times and now woks fine.

**Comment by sstrickx** [comment]
Will still provide a fix for that specific case... It should be handled properly.

**Comment by sstrickx** [comment]
Version 3.12.1 released. This should prevent the issue from occurring again.
