### ISSUE TITLE
NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper

### ISSUE THREAD

**Issue by peternees** [sstrickx/yahoofinance-api#108]
I get follow error with the 3.12.1.

Are you using a new library?

Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
	at yahoofinance.quotes.query1v7.QuotesRequest.<clinit>(QuotesRequest.java:29)
	at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:374)
	at yahoofinance.YahooFinance.get(YahooFinance.java:214)
	at yahoofinance.YahooFinance.get(YahooFinance.java:193)

**Comment by peternees** [comment]
ok, added jackson-databind-2.3.1.jar
