### ISSUE TITLE
Can't use this API anymore

### ISSUE THREAD

**Issue by avivblo** [sstrickx/yahoofinance-api#114]
When running this method:
`Stock stock = YahooFinance.get("CRERF");`

I get stackerror:
`
Nov 21, 2017 12:10:51 AM yahoofinance.quotes.QuotesRequest getResult
INFO: Sending request: http://download.finance.yahoo.com/d/quotes.csv?s=CRERF&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8s7&e=.csv
java.io.IOException: Server returned HTTP response code: 403 for URL: http://download.finance.yahoo.com/d/quotes.csv?s=CRERF&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8s7&e=.csv
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at yahoofinance.quotes.QuotesRequest.getResult(QuotesRequest.java:88)
	at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:361)
	at yahoofinance.YahooFinance.get(YahooFinance.java:91)
	at yahoofinance.YahooFinance.get(YahooFinance.java:75)
	at com.Main.checkStockAndPrint(Main.java:692)
	at com.Main.startCurrentScript(Main.java:600)
	at com.Main.main(Main.java:92)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://download.finance.yahoo.com/d/quotes.csv?s=CRERF&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8s7&e=.csv
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at yahoofinance.util.RedirectableRequest.openConnection(RedirectableRequest.java:54)
	at yahoofinance.util.RedirectableRequest.openConnection(RedirectableRequest.java:34)
	at yahoofinance.quotes.QuotesRequest.getResult(QuotesRequest.java:86)
	... 6 more
`

When trying to navigate to this URL in the browser I get this:

>It has come to our attention that this service is being used in violation of the Yahoo Terms of Service. As such, the service is being discontinued. For all future markets and equities data research, please refer to finance.yahoo.com.>

**Comment by sstrickx** [comment]
Hi, please try using the latest version of this library (3.12.2). From the logs you posted I can already see that you're using an older version.

**Comment by avivblo** [comment]
Thanks for the quick response! Upgrading to latest version has resolved this issue.
