### ISSUE TITLE
Index out of bounds with a YahooFinance.get(stockName) call

### ISSUE THREAD

**Issue by LucasMcQ** [sstrickx/yahoofinance-api#122]
Not really sure what to do with this error. My program was working earlier today. Now I'm getting this exception. I get this with the following call:

stock = YahooFinance.get("TSLA");

Dec 19, 2017 3:25:18 AM yahoofinance.quotes.QuotesRequest getResult
INFO: Sending request: http://finance.yahoo.com/d/quotes.csv?s=TSLA&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8s7&e=.csv
Dec 19, 2017 3:25:18 AM yahoofinance.quotes.QuotesRequest getResult
INFO: Parsing CSV line: <HTML>
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at yahoofinance.quotes.stock.StockQuotesRequest.parseCSVLine(StockQuotesRequest.java:126)
	at yahoofinance.quotes.stock.StockQuotesRequest.parseCSVLine(StockQuotesRequest.java:11)
	at yahoofinance.quotes.QuotesRequest.getResult(QuotesRequest.java:95)
	at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:355)
	at yahoofinance.YahooFinance.get(YahooFinance.java:85)
	at yahoofinance.YahooFinance.get(YahooFinance.java:69)
	at bots.TwitterBot.examineStock(TwitterBot.java:137)
	at bots.TwitterBot.searchTweets(TwitterBot.java:97)
	at bots.TwitterBot.main(TwitterBot.java:43)

**Comment by sstrickx** [comment]
Hi, I'm a bit surprised that it was working for you earlier today since that endpoint has already been decommissioned by Yahoo for most people.
Please use the latest version of the library (3.12.3) .

**Comment by LucasMcQ** [comment]
Thank you. Changing this in our pom.xml file worked!

**Comment by KasunDissanayake94** [comment]
Thank you very much. I changed my version to the latest version of the library (3.12.3). Then it worked!
