### ISSUE TITLE
Don't try to download bad tickets

### ISSUE THREAD

**Issue by alexeyulasevich** [sstrickx/yahoofinance-api#158]
**May be library should check(validate) ticker before download historical data.**
   
```
@Test
public void test() throws IOException {
        Calendar start = Calendar.getInstance();
        start.set(2020, Calendar.MAY, 5);
        Calendar end = Calendar.getInstance();
        end.set(2020, Calendar.MAY, 6);
        Map<String, Stock> stringStockMap = YahooFinance.get(new String[]{"IBM", "WFMI", "XXX"}, start, end, Interval.DAILY);
        assertNotNull(stringStockMap);
}
```

**I think it is better to return Stock object if data exists. And nothing for tickers if data not exists**.
Current behavior is just exception:

> java.io.FileNotFoundException: https://query1.finance.yahoo.com/v7/finance/download/WFMI?period1=1588680000&period2=1588766400&interval=1d&crumb=g6.ejeCoi%2FR
> 
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
> 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
> 	at yahoofinance.histquotes2.HistQuotes2Request.getResult(HistQuotes2Request.java:132)
> 	at yahoofinance.Stock.getHistory(Stock.java:327)
> 	at yahoofinance.YahooFinance.fetchHistoricalQuotes(YahooFinance.java:411)
> 	at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:405)
> 	at yahoofinance.YahooFinance.get(YahooFinance.java:321)
> 	at com.fundcount.quote.CYahooQuoteTest.test(CYahooQuoteTest.java:190)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
> 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
> 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> 	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:416)
> 	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:385)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
> 	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
> 	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
> 	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
> Caused by: java.io.FileNotFoundException: https://query1.finance.yahoo.com/v7/finance/download/WFMI?period1=1588680000&period2=1588766400&interval=1d&crumb=g6.ejeCoi%2FR
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
> 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
> 	at yahoofinance.util.RedirectableRequest.openConnection(RedirectableRequest.java:54)
> 	at yahoofinance.histquotes2.HistQuotes2Request.getResult(HistQuotes2Request.java:130)
> 	... 32 more
>

**Comment by jesstruck** [comment]
I strongly disagree, an exception is a great way for a method to respond, the queried stock does not exist, we could consider a special exception for this

If the method returns an empty data object we don't know if the ticker does not exist or yahoo did not have at info on it.

**Comment by alexeyulasevich** [comment]
In my case software user wants to download historical prices for many instruments. Some of tickers may be incorrect. Currently I avoid this by call method `get` for every instrument. If I get exception I write warning to log-file.

**Comment by alexeyulasevich** [comment]
By the way method [Yahoo.get(String[] symbols](https://financequotes-api.com/javadoc/yahoofinance/YahooFinance.html#get-java.lang.String:A-)) return only existing data.

**Comment by eztam-** [comment]
@alexeyulasevich The behaviour of [Yahoo.get(String[] symbols](https://financequotes-api.com/javadoc/yahoofinance/YahooFinance.html#get-java.lang.String:A-)) is consistent to [get(String[] symbols, Calendar from, Calendar to,Interval interval)](https://financequotes-api.com/javadoc/yahoofinance/YahooFinance.html#get-java.lang.String:A-java.util.Calendar-java.util.Calendar-yahoofinance.histquotes.Interval-)

The problem with your code is, that all three (IBM, WFMI, XXX) are actually valid symbols. See [response from Yahoo](https://query1.finance.yahoo.com/v7/finance/quote?symbols=IBM%2CWFMI%2CXXX). If you would add an actual invalid symbol like X123, then you would also not see any exception and the result would be skipped.

The problem is a different one. As said, all three are valid symbols but only IBM has historical quotes available. So the CSV request for WFMI returns HTTP status code 404 ([see request](https://query1.finance.yahoo.com/v7/finance/download/WFMI?period1=1588672800&period2=1588759200&interval=1d&crumb=W2xuGJjIVz.)).

The only way to identify this issue without throwing an Exception would be, to return null for the historical quotes in case of a 404 response. But this would hide potential other reasons that might return a 404.

Unfortunately theres no solid way to fix it, therefore I'd suggest to close the issue.
