### ISSUE TITLE
java.io.FileNotFoundException when making numerous requests on getHistory

### ISSUE THREAD

**Issue by saghassy** [sstrickx/yahoofinance-api#159]
Hello, is there any advice on doing numerous getHistory requests? It seems that yahoo is throttling me after some time and I start seeing a lot of FileNotFoundException which then go away after a while. The stocks themselves are valid, example: 
`
java.io.FileNotFoundException: https://query1.finance.yahoo.com/v7/finance/download/ANAT?period1=1590174000&period2=1591470000&interval=1d&crumb=k2OOWzEa62D
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1964)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:552)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1963)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1531)`

I tried doing a CrumbManager.refresh(); after this happens, but it seems that this does NOT actually change the crumb because the setCookie() request returns the same cookie, which I believe causes the crumb to also be the same. 

I am using yahoo finance to go through a large list of stocks and filter them based on my criteria and I need daily price history for the stocks.

My code snippet is below, the lookback is 15 days.

        try {
            priceHistory = stock.getHistory(getXDaysAgo(lookback), Interval.DAILY);
        } catch (IOException e) {
            if (numRetries > 0) {
                e.printStackTrace();
                System.err.println("Failed to get data for " + stock.getSymbol() + " " + e + " retrying!");
                try {
                    Thread.sleep(1000);
                    CrumbManager.refresh();
                } catch (InterruptedException f) {
                } catch (IOException e1) {
                }
                return getTradeabilityScore(stock, lookback, numRetries - 1);
            } else {
                System.err.println("Giving up!!!! Failed to get history for " + stock.getSymbol() + " " + e);
                return null;
            }
        }

**Comment by emisaacson** [comment]
Ive been able to work around this by flipping urls when there's a failure. the library has a JVM property to set the url so i've been doing this:

```
    for {
          _ <- IO(log.info(s"Fetching fund data for $ticker")).attempt
          data <- IO(YahooFinance.get(ticker, calendarFrom, calendarTo, Interval.DAILY))
            .recoverWith {
              case _: FileNotFoundException =>
                for {
                  flip <- flipper.getAndUpdate(!_)
                  _ = if (flip) System.setProperty("yahoofinance.baseurl.histquotes2", "https://query1.finance.yahoo.com/v7/finance/download/")
                      else System.setProperty("yahoofinance.baseurl.histquotes2", "https://query2.finance.yahoo.com/v7/finance/download/")
                  dataRetry <- IO(YahooFinance.get(ticker, calendarFrom, calendarTo, Interval.DAILY))
                } yield dataRetry
            }
    } yield data
```
