### ISSUE TITLE
This is probably easily solved, but nothing can be invoked!

### ISSUE THREAD

**Issue by DenDen747** [sstrickx/yahoofinance-api#175]
@sstrickx
I'm using IntelliJ IDEA, and every time I try to run anything, It does this.

Here is the code:
```java
Stock stock = new Stock("AAPL");
System.out.println(stock.getQuote().getPrice());
```
And it says that System.out.println(stock.getQuote().getprice()); has the following error:
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "yahoofinance.quotes.stock.StockQuote.getPrice()" because "this.quote" is null
	at yahoofinance.Stock.toString(Stock.java:530)
	at java.base/java.lang.String.valueOf(String.java:3367)
	at java.base/java.io.PrintStream.println(PrintStream.java:1047)
	at coin.YahooStockTest.Main.main(Main.java:8)
```

This doesn't only happen for just this example. It happens when I try to use anything. How do I fix this?

**Comment by DenDen747** [comment]
Figured it out!
