### ISSUE TITLE
I'm getting a lot of java.io.FileNotFoundException

### ISSUE THREAD

**Issue by charbelgereige** [sstrickx/yahoofinance-api#19]
http://ichart.yahoo.com/table.csv?s=STMP&a=7&b=18&c=2015&d=7&e=18&f=2015&g=m&ignore=.csv

21:41:53.583 [pool-2-thread-2] INFO  com.oak.external.spring.config.ApplicationConfig - Sending request: http://ichart.yahoo.com/table.csv?s=STMP&a=7&b=18&c=2015&d=7&e=18&f=2015&g=m&ignore=.csv
21:42:00.827 [pool-2-thread-2] ERROR com.oak.external.spring.config.ApplicationConfig - error getting price from Yahoo for [Ljava.lang.String;@21ba09a3
java.io.FileNotFoundException: http://ichart.yahoo.com/table.csv?s=STMP&a=7&b=18&c=2015&d=7&e=18&f=2015&g=m&ignore=.csv
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_45]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_45]
	at yahoofinance.histquotes.HistQuotesRequest.getResult(HistQuotesRequest.java:107) ~[bin/:?]
	at yahoofinance.Stock.getHistory(Stock.java:296) ~[bin/:?]
	at yahoofinance.YahooFinance.fetchHistoricalQuotes(YahooFinance.java:382) ~[bin/:?]
	at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:376) ~[bin/:?]
	at yahoofinance.YahooFinance.get(YahooFinance.java:247) ~[bin/:?]
	at com.oak.external.finance.app.marketdata.api.impl.yahoo.YahooDataConnector.getEconomics(YahooDataConnector.java:49) [bin/:?]
	at com.oak.external.finance.app.marketdata.api.impl.MarketDataPollingProviderImpl.startThread(MarketDataPollingProviderImpl.java:55) [bin/:?]
	at com.oak.external.finance.app.marketdata.api.impl.MarketDataPollingProviderImpl$1.run(MarketDataPollingProviderImpl.java:45) [bin/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_45]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]

I saw someone posting similar problem. is there a way around it?

**Comment by sstrickx** [comment]
Hi,

You are requesting the historical data from AUG18 2015 to AUG18 2015. It looks like Yahoo Finance doesn't like this. When I find some time, I'll put a check on this.
If you adjust your request to get data from AUG17 2015 to AUG18 2015, you'll see that it works fine. (would just return the values for AUG17)

I'm not really sure what you're trying to achieve though. Intraday history is not available. The smallest granularity you can get is "daily". This can be defined by using one of the methods where you can pass the Interval (for example: http://financequotes-api.com/javadoc/yahoofinance/YahooFinance.html#get-java.lang.String:A-java.util.Calendar-java.util.Calendar-yahoofinance.histquotes.Interval- )

**Comment by charbelgereige** [comment]
oh ok, thank you!
I'll change that.

thanks a lot for the library
