### ISSUE TITLE
v3.17 is working?

### ISSUE THREAD

**Issue by emidesy** [sstrickx/yahoofinance-api#197]
Hi! i use the last version, but a few days its not working.
I proof single stock in a clean code and nothing.

Thanks!

**Comment by StefanLober** [comment]
Hello,
what environment did you use to get the stock data?
I have used this API v3.17 in an Android app and noticed that it stopped working a few days ago. There is always this error:
```
java.io.FileNotFoundException: https://query1.finance.yahoo.com/v7/finance/quote?symbols=AMD.DE
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26)
        at yahoofinance.quotes.query1v7.QuotesRequest.getResult(QuotesRequest.java:74)
        at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:381)
        at yahoofinance.YahooFinance.get(YahooFinance.java:98)
        at yahoofinance.YahooFinance.get(YahooFinance.java:82)
```

However, using the URL in a browser works fine and testing the API v3.17 getting the same symbol in a simple command line Java project on Windows also works.

**Comment by RamitPahwa** [comment]
Any WorkAround for this in Android ? Need this for a prototype @StefanLober @sstrickx

**Comment by emidesy** [comment]
Hi! Exactly the same error for me, with android app, @StefanLober

**Comment by emidesy** [comment]
There is a fork of this project, https://github.com/sfuhrm/yahoofinance-api
But it doesnt work to me,

**Comment by StefanLober** [comment]
Setting a User-Agent with setRequestProperty fixes the problem on Android. It seems that the Android implementation of HttpURLConnection does not set this property, while the default Java implementation does set it.
Propably, Yahoo has made a change in the recent past, so that requests without User-Agent no longer work.

**Comment by emidesy** [comment]
> 

Thanks!! its work, 

I add this line:  System.setProperty("http.agent", "");
