### ISSUE TITLE
Error Code 503

### ISSUE THREAD

**Issue by zytan89** [sstrickx/yahoofinance-api#225]
Caused by: java.io.IOException: Server returned HTTP response code: 503 for URL: https://finance.yahoo.com/quote/%5EGSPC/options
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at yahoofinance.util.RedirectableRequest.openConnection(RedirectableRequest.java:54)
	at yahoofinance.util.RedirectableRequest.openConnection(RedirectableRequest.java:34)
	at yahoofinance.histquotes2.CrumbManager.setCookie(CrumbManager.java:52)
	

I am currently getting error 503 when getting request. Anyone facing similar issue?

**Comment by code-monkey-101** [comment]
Yeah, since yesterday. This fixed it for me:

![image](https://github.com/sstrickx/yahoofinance-api/assets/32152103/6907713c-77e8-45dd-8dfe-a15d9e3c131e)

You might also have to be on Java 1.8 to set the user agent like that. I've tried a newer Java version once and it didn't work.

**Comment by zytan89** [comment]
I tested on java 17 it seem to work fine. You are my savior.

**Comment by BrianHee** [comment]
@code-monkey-101 Bless you 🙏

**Comment by joshualj** [comment]
Hi All, 

My JDK is 1.8, and I have filled in the "User-Agent" value. 
But, with the debugger, I see a responseCode of -1 downstream of the new call 

`redirectableRequest.openConnection(requestProperties);`

Any advice?


![Screenshot 2024-07-10 at 5 34 59 PM](https://github.com/sstrickx/yahoofinance-api/assets/91722712/9a7f0b2f-d140-46b2-852b-c6eb874e9200)
![Screenshot 2024-07-10 at 4 37 00 PM](https://github.com/sstrickx/yahoofinance-api/assets/91722712/108d3f7d-a2fe-42ff-af65-950ab033ca9c)
![Screenshot 2024-07-10 at 5 36 58 PM](https://github.com/sstrickx/yahoofinance-api/assets/91722712/7aafc413-6b05-4ead-8e25-3b2946444399)


> Yeah, since yesterday. This fixed it for me:
> 
> ![image](https://private-user-images.githubusercontent.com/32152103/322891758-6907713c-77e8-45dd-8dfe-a15d9e3c131e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MzA5OTEsIm5iZiI6MTcyMDYzMDY5MSwicGF0aCI6Ii8zMjE1MjEwMy8zMjI4OTE3NTgtNjkwNzcxM2MtNzdlOC00NWRkLThkZmUtYTE1ZDllM2MxMzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE2NTgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3N2FiNjY2ZGVkMWNmNGFkOWVjZDg0NThmNGQ5YzU3NGE4ZGMyZGFhOTUwNDdmM2QyZTAyNTc1NjdlNmY1NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ku712qe_dpvvWG11RAJuveZUkIViSkcxyUC5_wYAUl8)
> 
> You might also have to be on Java 1.8 to set the user agent like that. I've tried a newer Java version once and it didn't work.
