### ISSUE TITLE
Parser should respect non-numeric values

### ISSUE THREAD

**Issue by dkuppitz** [sstrickx/yahoofinance-api#29]
```
INFO: Parsing CSV line: \"AlphaClone Alternative Alpha ET\",\"ALFA\",\"USD\",\"PCX\",35.62,N/A,\"ALFA\",3600,\"ALFA\",35.56,N/A,\"ALFA\",1400,\"ALFA\",35.56,\"ALFA\",100,\"ALFA\",\"1/27/2016\",\"11:35am\",35.83,35.83,35.56,35.83,1268,45842,47.66,33.00,36.69,40.25,\"ALFA\",N/A,\"ALFA\",\"ALFA\",N/A,\"ALFA\",N/A,\"ALFA\",N/A,\"ALFA\",N/A,N/A,0.00,0.00,N/A,nan,0.00,N/A,N/A,0.00,N/A,N/A,0.00,N/A,N/A,N/A
Jan 27, 2016 5:52:37 PM yahoofinance.Utils getBigDecimal
INFO: Failed to parse: nan
java.lang.NumberFormatException
	at java.math.BigDecimal.<init>(BigDecimal.java:494)
	at java.math.BigDecimal.<init>(BigDecimal.java:383)
	at java.math.BigDecimal.<init>(BigDecimal.java:806)
	at yahoofinance.Utils.getBigDecimal(Utils.java:70)
	at yahoofinance.quotes.stock.StockQuotesData.getStats(StockQuotesData.java:71)
	at yahoofinance.quotes.stock.StockQuotesData.getStock(StockQuotesData.java:107)
	at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:353)
	at yahoofinance.YahooFinance.get(YahooFinance.java:79)
	at yahoofinance.YahooFinance.get(YahooFinance.java:63)
```

**Comment by dkuppitz** [comment]
Just got another parser error:

```
INFO: Sending request: http://finance.yahoo.com/d/quotes.csv?s=USD&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8&e=.csv
Jan 27, 2016 6:33:36 PM yahoofinance.quotes.QuotesRequest getResult
INFO: Parsing CSV line: \"ProShares Ultra Semiconductors\",\"USD\",\"USD\",\"PCX\",68.66,N/A,\"USD\",300,\"USD\",67.96,N/A,\"USD\",500,\"USD\",68.16,\"USD\",100,\"USD\",\"1/27/2016\",\"11:49am\",67.39,68.00,66.45,68.16,6872,8671,104.99,52.00,79.59,77.18,\"USD\",N/A,\"USD\",\"USD\",N/A,\"USD\",N/A,\"USD\",N/A,\"USD\",N/A,N/A,N/A,N/A,N/A,N/A,0.00,N/A,N/A,0.00,N/A,N/A,0.00,N/A,N/A,N/A
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at yahoofinance.quotes.stock.StockQuotesRequest.parseCSVLine(StockQuotesRequest.java:138)
	at yahoofinance.quotes.stock.StockQuotesRequest.parseCSVLine(StockQuotesRequest.java:11)
	at yahoofinance.quotes.QuotesRequest.getResult(QuotesRequest.java:93)
	at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:349)
	at yahoofinance.YahooFinance.get(YahooFinance.java:79)
	at yahoofinance.YahooFinance.get(YahooFinance.java:63)
```

Not a number problem though; not sure why it fails there.

**Comment by dkuppitz** [comment]
I just realized that the `NumberFormatException` is actually being caught. However, I wouldn't expect to see a stack trace in that case. Should be more like:

```java
YahooFinance.logger.log(Level.INFO, "Failed to parse: " + data)
```

or:

```java
YahooFinance.logger.log(Level.INFO, "Failed to parse: " + data + "\n\t" + e.getMessage())
```

But definitely no stack trace, since this is totally misleading. Nobody cares about about a stack trace if the exception was caught / handled.
