### ISSUE TITLE
NumberFormatException in StockQuotesData.getStats() function

### ISSUE THREAD

**Issue by virtualSharif** [sstrickx/yahoofinance-api#52]
Currently I am using the 1.3.0 version of maven dependency in my sample java project.

I got this exception  : 
java.lang.NumberFormatException: null
	at java.math.BigDecimal.<init>(BigDecimal.java:494) ~[na:1.8.0_101]
	at java.math.BigDecimal.<init>(BigDecimal.java:383) ~[na:1.8.0_101]
	at java.math.BigDecimal.<init>(BigDecimal.java:806) ~[na:1.8.0_101]
	at yahoofinance.Utils.getBigDecimal(Utils.java:70) ~[YahooFinanceAPI-1.3.0.jar:na]
	at yahoofinance.quotes.stock.StockQuotesData.getStats(StockQuotesData.java:69) [YahooFinanceAPI-1.3.0.jar:na]
	at yahoofinance.quotes.stock.StockQuotesData.getStock(StockQuotesData.java:105) [YahooFinanceAPI-1.3.0.jar:na]
	at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:336) [YahooFinanceAPI-1.3.0.jar:na]
	at yahoofinance.YahooFinance.get(YahooFinance.java:191) [YahooFinanceAPI-1.3.0.jar:na]
	at yahoofinance.YahooFinance.get(YahooFinance.java:171) [YahooFinanceAPI-1.3.0.jar:na]
	at com.xxx.xxx.xxx.StockExchangeService.getInformation(StockExchangeService.java:34) [classes/:na]

Sample code of my application where i have used the YahooFinance methods :

Line 33:  String[] symbols = new String[] {"INTC", "BABA", "TSLA", "AIR.PA", "YHOO"};
Line 34:  Map<String, Stock> stocks = YahooFinance.get(newSymbols);

Please fix it or let me know if I am wrong somewhere.

**Comment by sstrickx** [comment]
Could you try with the latest version of the API? (3.4.0)
I'm unable to reproduce the problem you seem to encounter.

Not sure if your example gives the full picture either. Your variable on line 33 is called `symbols`, while the one you use on line 34 is called `newSymbols`. But I think that's just something that happened when copy-pasting the code over here.

Please let me know if you still have the issue with the latest version.

**Comment by virtualSharif** [comment]
I have updated to latest version.

Hence, the problem is solved.
Thanks @sstrickx
