### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by yogi-dmt** [sstrickx/yahoofinance-api#66]
Simple getHistory() request doesn't work for some stocks...

This one failed for SNOAW, DELTW, KTOVW, CYTXW, ZIONZ, GFNSL, ZNWAA, as well as others.

```
Stock s = YahooFinance.get("SNOAW");
s.getHistory();
```

```
Feb 23, 2017 1:40:17 PM yahoofinance.quotes.QuotesRequest getResult
INFO: Sending request: http://finance.yahoo.com/d/quotes.csv?s=SNOAW&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8s7&e=.csv
Feb 23, 2017 1:40:17 PM yahoofinance.quotes.QuotesRequest getResult
INFO: Parsing CSV line: \"Sonoma Pharmaceuticals, Inc.\",\"SNOAW\",\"USD\",\"NCM\",0.520,N/A,\"SNOAW\",9900,\"SNOAW\",0.460,N/A,\"SNOAW\",2000,\"SNOAW\",0.451,\"SNOAW\",3484,\"SNOAW\",\"2/23/2017\",\"1:02pm\",0.500,0.540,0.451,0.500,27397,N/A,0.500,0.451,0.000,0.000,\"SNOAW\",N/A,\"SNOAW\",\"SNOAW\",N/A,\"SNOAW\",N/A,\"SNOAW\",N/A,\"SNOAW\",N/A,N/A,N/A,N/A,N/A,N/A,0.000,N/A,N/A,0.000,N/A,N/A,0.000,N/A,0.00,N/A,0.000
Feb 23, 2017 1:40:17 PM yahoofinance.histquotes.HistQuotesRequest getResult
INFO: Sending request: http://ichart.yahoo.com/table.csv?s=SNOAW&a=1&b=23&c=2016&d=1&e=23&f=2017&g=m&ignore=.csv
Exception in thread "main" java.io.FileNotFoundException: http://ichart.yahoo.com/table.csv?s=SNOAW&a=1&b=23&c=2016&d=1&e=23&f=2017&g=m&ignore=.csv
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at yahoofinance.histquotes.HistQuotesRequest.getResult(HistQuotesRequest.java:117)
	at yahoofinance.Stock.getHistory(Stock.java:298)
	at yahoofinance.Stock.getHistory(Stock.java:278)
	at yahoofinance.Stock.getHistory(Stock.java:242)
	at yahoofinance.Stock.getHistory(Stock.java:208)
	at stuff.Data.main(Data.java:175)
```

**Comment by derrix060** [comment]
Are you tring to get the Sonoma Pharmaceuticals stock? If yes, as you can see here: https://finance.yahoo.com/quote/SNOA the right stock is "SNOA". The others one, when I try to search in http://finance.yahoo.com/, it get error. Because this, the problem is in Yahoo, not in this project.

**Comment by sstrickx** [comment]
It looks indeed like this data is not available from the Yahoo ichart API.
However, some of these do seem to be available from some of Yahoo's other APIs. Might give those a try soon (#67).

**Comment by yogi-dmt** [comment]
Only reason i mentioned is because the isValid() method seems to be working for these. Thanks for the responses
