### ISSUE TITLE
Another error after 1.2 upgrade.Plz check

### ISSUE THREAD

**Issue by jbdundas** [sstrickx/yahoofinance-api#7]
Feb 15, 2015 7:45:37 PM yahoofinance.quotes.QuotesRequest getResult
INFO: Sending request: http://finance.yahoo.com/d/quotes.csv?s=ZB%5EF&f=n0sc4x0a0b2sa5sb0b3sb6sl1sk3sd1t1o0p0g0h0v0a2k0j0m3m4sj2sss1sj1sf6sr1q0d0y0e0e7e9e8r0r5p6p5b4s6j4t8&e=.csv
Feb 15, 2015 7:45:38 PM yahoofinance.quotes.QuotesRequest getResult
INFO: Parsing CSV line: \"ZB^F\",\"ZB^F\",\"|v
Exception in thread "Timer-0" java.lang.StringIndexOutOfBoundsException: String index out of range: -16
	at java.lang.String.substring(String.java:1954)
	at yahoofinance.quotes.stock.StockQuotesRequest.parseCSVLine(StockQuotesRequest.java:134)
	at yahoofinance.quotes.stock.StockQuotesRequest.parseCSVLine(StockQuotesRequest.java:11)
	at yahoofinance.quotes.QuotesRequest.getResult(QuotesRequest.java:93)
	at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:332)
	at yahoofinance.YahooFinance.get(YahooFinance.java:76)
	at yahoofinance.YahooFinance.get(YahooFinance.java:61)
	at com.jnd.analysis.StockAnalysisBatchClass.processStockFundamentals(StockAnalysisBatchClass.java:43)
	at com.jnd.stocksparser.StockBatchProcess.startStockDetailsProcess(StockBatchProcess.java:41)
	at com.jnd.stocksparser.StockBatchProcess.triggerStockBatchProcess(StockBatchProcess.java:61)
	at com.jnd.stocksparser.Main.run(Main.java:68)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by sstrickx** [comment]
Hi Jitesh,
This doesn't seem to fail on my end... It looks like you didn't receive the full result from Yahoo Finance. Is it possible that this was caused by a temporary network issue?

Yahoo Finance doesn't seem to be able to find any decent results for ZB^F either, which stock are you trying to retrieve?

**Comment by sstrickx** [comment]
The request for ZB^F from my side: 

INFO: Sending request: http://finance.yahoo.com/d/quotes.csv?s=ZB%5EF&f=n0sc4x0a0b2sa5sb0b3sb6sl1sk3sd1t1o0p0g0h0v0a2k0j0m3m4sj2sss1sj1sf6sr1q0d0y0e0e7e9e8r0r5p6p5b4s6j4t8&e=.csv
Feb 16, 2015 2:40:30 PM yahoofinance.quotes.QuotesRequest getResult
INFO: Parsing CSV line: \"ZB^F\",\"ZB^F\",\"4t8\",\"N/A\",N/A,N/A,\"ZB^F\",N/A,\"ZB^F\",N/A,N/A,\"ZB^F\",N/A,\"ZB^F\",0.00,\"ZB^F\",N/A,\"ZB^F\",\"N/A\",\"12:24am\",N/A,N/A,N/A,N/A,N/A,0,N/A,N/A,N/A,N/A,\"ZB^F\",N/A,\"ZB^F\",\"ZB^F\",-,\"ZB^F\",N/A,\"ZB^F\",N/A,\"ZB^F\",\"N/A\",\"N/A\",N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ZB^F
--------------------------------
symbol: ZB^F
name: ZB^F
currency: 4t8
stockExchange: N/A
quote: Ask: 0, Bid: 0, Price: 0.00, Prev close: 0
stats: EPS: 0, PE: 0, PEG: 0
dividend: Pay date: /, Ex date: /, Annual yield: 0%
history: null
--------------------------------

**Comment by sstrickx** [comment]
Hi Jitesh,

Since I'm unable to reproduce the issue and didn't hear back from you in a while, this issue will be closed.
If you still encounter any problems with the API, please don't hesitate to create a new issue.
