### ISSUE TITLE
StringOutOfBoundException

### ISSUE THREAD

**Issue by macphilips** [sstrickx/yahoofinance-api#80]
The occurred while I was retrieving stock quote while I was connect to a Wi-Fi with no internet access  

STACK_TRACE=java.lang.StringIndexOutOfBoundsException: length=16; regionStart=0; regionLength=-1
at java.lang.String.startEndAndLength(String.java:298)
at java.lang.String.substring(String.java:1087)
at yahoofinance.quotes.stock.StockQuotesRequest.parseCSVLine(StockQuotesRequest.java:126)
at yahoofinance.quotes.stock.StockQuotesRequest.parseCSVLine(StockQuotesRequest.java:11)
at yahoofinance.quotes.QuotesRequest.getResult(QuotesRequest.java:98)
at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:355)
at yahoofinance.YahooFinance.get(YahooFinance.java:207)
at yahoofinance.YahooFinance.get(YahooFinance.java:186)
at com.udacity.stockhawk.sync.QuoteSyncJob.getQuotes(QuoteSyncJob.java:70)
at com.udacity.stockhawk.sync.QuoteIntentService.onHandleIntent(QuoteIntentService.java:18)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:158)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by sstrickx** [comment]
It looks like the library actually received some data, so I guess in this case it was receiving a landing page of the Wi-Fi...
This is a bit of special case that I absolutely didn't foresee. Thanks for reporting this.
The exception should definitely be handled better (or there should first be some sanity check on the content received by the library). I'll refer this to #68.
