### ISSUE TITLE
Retrieving Null Values

### ISSUE THREAD

**Issue by Nehareeka** [sstrickx/yahoofinance-api#81]
Hi
The sample code provided in README file, all return a null values.

```
Stock stock = new Stock("INTC");
stock.getQuote(true);
stock.print();
```

Above is one of the codes i have been trying and below is the stack trace

 yahoofinance.quotes.QuotesRequest getResult
INFO: Sending request: http://finance.yahoo.com/d/quotes.csv?s=INTC&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8s7&e=.csv
yahoofinance.Stock update
SEVERE: Failed to update Stock with symbol: INTC
INTC
--------------------------------
symbol: INTC
name: null
currency: null
stockExchange: null
quote: null
stats: null
dividend: null
history: null
--------------------------------

Could you help me with this issue?

**Comment by yogi-dmt** [comment]
Same here. getQuote() seems to return a null object. It was working before, maybe Yahoo changed their site...

**Comment by sstrickx** [comment]
Hi,
This actually still works fine on my end... Which version of the library are you using?
Do you still see the issue right now?

**Comment by LoMonacoSBU15** [comment]
I had the same problem until i updated my dependency to use version 3.8.0, hope this helps

**Comment by Nehareeka** [comment]
Updated the version from 3.6.1 to 3.8.0
the values are coming null for name, currency and history

the output is


symbol: INTC
name: null
currency: null
stockExchange: null
quote: Ask: 36.32, Bid: 36.25, Price: 36.32, Prev close: 36.12
stats: EPS: 2.31, PE: 15.72, PEG: 1.51
dividend: Pay date: Thu Jun 01 09:30:00 IST 2017, Ex date: Wed May 03 09:30:00 IST 2017, Annual yield: 3.02%
history: null

**Comment by yogi-dmt** [comment]
So i updated to the latest version and looks like it's working now. Thanks for the help.

**Comment by sstrickx** [comment]
@Nehareeka can you show the logs of your latest attempt?

**Comment by yogi-dmt** [comment]
now i'm getting a 999 error from the server...

java.io.IOException: Server returned HTTP response code: 999 for URL: http://download.finance.yahoo.com/d/quotes.csv?s=YECO&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8s7&e=.csv
	at sun.reflect.GeneratedConstructorAccessor11.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at yahoofinance.quotes.QuotesRequest.getResult(QuotesRequest.java:88)
	at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:361)
	at yahoofinance.YahooFinance.get(YahooFinance.java:91)
	at yahoofinance.YahooFinance.get(YahooFinance.java:75)
	at StockData.getStock(StockData.java:77)
	at StockData.<init>(StockData.java:28)
	at ProgramLogic.main(ProgramLogic.java:30)
Caused by: java.io.IOException: Server returned HTTP response code: 999 for URL: http://download.finance.yahoo.com/d/quotes.csv?s=YECO&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8s7&e=.csv
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at yahoofinance.util.RedirectableRequest.openConnection(RedirectableRequest.java:54)
	at yahoofinance.util.RedirectableRequest.openConnection(RedirectableRequest.java:34)
	at yahoofinance.quotes.QuotesRequest.getResult(QuotesRequest.java:86)
	... 6 more

Apparently it's not a "real" server code and some people suggested changing the user agent. I did that and still receive the 999 response code. Seems to only happen on some of the requests, not all.

**Comment by yogi-dmt** [comment]
Anyone else getting a 999 error code..?

```
java.io.IOException: Server returned HTTP response code: 999 for URL: http://download.finance.yahoo.com/d/quotes.csv?s=BBY&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8s7&e=.csv
	at sun.reflect.GeneratedConstructorAccessor11.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at yahoofinance.quotes.QuotesRequest.getResult(QuotesRequest.java:88)
	at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:361)
	at yahoofinance.YahooFinance.get(YahooFinance.java:91)
	at yahoofinance.YahooFinance.get(YahooFinance.java:75)
	at StockData.getStock(StockData.java:77)
	at StockData.<init>(StockData.java:28)
	at ProgramLogic.main(ProgramLogic.java:30)
Caused by: java.io.IOException: Server returned HTTP response code: 999 for URL: http://download.finance.yahoo.com/d/quotes.csv?s=BBY&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8s7&e=.csv
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at yahoofinance.util.RedirectableRequest.openConnection(RedirectableRequest.java:54)
	at yahoofinance.util.RedirectableRequest.openConnection(RedirectableRequest.java:34)
	at yahoofinance.quotes.QuotesRequest.getResult(QuotesRequest.java:86)
	... 6 more
```

**Comment by Nehareeka** [comment]
@sstrickx no error logs for my latest attempt after shifting to version 3.8.0
however some values still show null like name, history, stockexchange, currency

**Comment by sstrickx** [comment]
@Nehareeka Even the INFO logs would could be quite useful to investigate this further, thanks.

**Comment by Nehareeka** [comment]
eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

org.eclipse.egit.ui
Warning
Sat Jun 10 18:18:45 IST 2017
Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\NEHA'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

**Comment by Nehareeka** [comment]
yahoofinance.quotes.QuotesRequest getResult
INFO: Sending request: http://download.finance.yahoo.com/d/quotes.csv?s=INTC&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8s7&e=.csv
yahoofinance.quotes.QuotesRequest getResult
INFO: Parsing CSV line: \"Intel Corporation\",\"INTC\",\"USD\",\"NMS\",36.05,N/A,\"INTC\",600,\"INTC\",35.72,N/A,\"INTC\",1000,\"INTC\",35.71,\"INTC\",2969074,\"INTC\",\"6/9/2017\",\"4:00pm\",36.50,36.48,35.31,36.56,33322053,21708800,38.45,30.44,36.22,36.11,\"INTC\",4709000000,\"INTC\",\"INTC\",N/A,\"INTC\",168.16B,\"INTC\",4706833000,\"INTC\",\"6/1/2017\",\"5/3/2017\",1.09,3.01,2.31,2.86,0.74,2.97,15.46,1.53,2.57,2.84,14.19,60.48B,23.67B,39.90,3.73
yahoofinance.Stock update
INFO: Updated Stock with symbol: INTC
INTC
--------------------------------
symbol: INTC
name: null
currency: null
stockExchange: null
quote: Ask: 36.05, Bid: 35.72, Price: 35.71, Prev close: 36.48
stats: EPS: 2.31, PE: 15.46, PEG: 1.53
dividend: Pay date: Thu Jun 01 09:30:00 IST 2017, Ex date: Wed May 03 09:30:00 IST 2017, Annual yield: 3.01%
history: null
--------------------------------

**Comment by lynnwilliam** [comment]
This issue still seams to be present in YahooFinanceAPI-3.8.0
using the following code 
Stock yahooStock = yahooResult.get("ADMP");
List <HistoricalQuote> yahooHistory = yahooStock.getHistory();
//not showing iteration code
quoteX.getOpen()  //works fine
quoteX.getVolume()  THROWS A NULL POINTER EXCEPTION

**Comment by chadworth** [comment]
`getVolume()` is working for me

```
      System.setProperty("org.slf4j.simpleLogger.defaultLogLevel", "debug");
      Stock stock = new Stock("INTC");
      StockQuote quote = stock.getQuote(true);
      System.out.println("Volume: " + quote.getVolume());
      stock.print();
```

>[main] INFO yahoofinance.quotes.QuotesRequest - Sending request: http://download.finance.yahoo.com/d/quotes.csv?s=INTC&f=7nsc4xab2sa5sbb3sb61sk3sd1t1opghva2kjm3m4sj2ss89s1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8s&e=.csv
[main] INFO yahoofinance.quotes.QuotesRequest - Parsing CSV line: \"Intel Corporation\",\"INTC\",\"USD\",\"NMS\",35.76,N/A,\"INTC\",4700,\"INTC\",35.75,N/A,\"INTC\",14800,\"INTC\",35.75,\"INTC\",400,\"INTC\",\"8/16/2017\",\"11:44am\",35.98,36.00,35.72,36.07,6673231,21519900,38.45,33.23,34.96,35.67,\"INTC\",4699000000,\"INTC\",\"INTC\",N/A,\"INTC\",167.99B,\"INTC\",4696838000,\"INTC\",\"9/1/2017\",\"8/3/2017\",1.09,3.04,2.62,3.01,0.82,3.09,13.65,1.37,2.47,2.74,14.60,61.71B,24.70B,39.81,4.63
[main] INFO yahoofinance.Stock - Updated Stock with symbol: INTC
Volume: 6673231
INTC
--
log: org.slf4j.impl.SimpleLogger(yahoofinance.Stock)
symbol: INTC
name: null
currency: null
stockExchange: null
quote: Ask: 35.76, Bid: 35.75, Price: 35.75, Prev close: 36.00
stats: EPS: 2.62, PE: 13.65, PEG: 1.37
dividend: Pay date: Thu Aug 31 21:00:00 PDT 2017, Ex date: Wed Aug 02 21:00:00 PDT 2017, Annual yield: 3.04%
history: null

**Comment by sstrickx** [comment]
Hi,

I'd like to point out that the Stock class wasn't really supposed to be initialized like that. The first time you should use the static methods in the `YahooFinance` class. That way the `name`, `currency` and `stockExchange` fields will also be set correctly:
```java
Stock stock = YahooFinance.get("INTC");
stock.print();
```
Once you have the `stock` object, calling the `stock.getQuote(true)` method will indeed force an update of the `quote`, `stats` and `dividend` fields. Calling `stock.getQuote(false)` or just `stock.getQuote()` will just return the values without forcing an update.

Furthermore, I don't see how `StockQuote.getVolume()` could throw a `NullPointerException` at all. It's just returning the instance variable `volume`. It can definitely return `null` but that's normal behavior when Yahoo Finance doesn't give the volume. Definitely worth checking your data for `null` values before trying to do any operations on them.
