### ISSUE TITLE
Server response code 999

### ISSUE THREAD

**Issue by yogi-dmt** [sstrickx/yahoofinance-api#82]
Is anyone else getting a 999 response code when requesting a quote?

```
java.io.IOException: Server returned HTTP response code: 999 for URL: http://download.finance.yahoo.com/d/quotes.csv?s=NVEE&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8s7&e=.csv
	at sun.reflect.GeneratedConstructorAccessor11.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at yahoofinance.quotes.QuotesRequest.getResult(QuotesRequest.java:88)
	at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:361)
	at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:379)
	at yahoofinance.YahooFinance.get(YahooFinance.java:172)
	at StockData.getStock(StockData.java:89)
	at StockData.<init>(StockData.java:28)
	at ProgramLogic.main(ProgramLogic.java:30)
Caused by: java.io.IOException: Server returned HTTP response code: 999 for URL: http://download.finance.yahoo.com/d/quotes.csv?s=NVEE&f=nsc4xab2sa5sbb3sb6sl1sk3sd1t1opghva2kjm3m4sj2sss1sj1sf6sr1qdyee7e9e8rr5p6p5b4s6j4t8s7&e=.csv
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at yahoofinance.util.RedirectableRequest.openConnection(RedirectableRequest.java:54)
	at yahoofinance.util.RedirectableRequest.openConnection(RedirectableRequest.java:34)
	at yahoofinance.quotes.QuotesRequest.getResult(QuotesRequest.java:86)
```

Apparently 999 isn't a standard code. Is it possible they're blocking me for sending too many requests?

**Comment by sstrickx** [comment]
They do block connections that have been sending too many requests. It seems that this is the reason in this case.
